### ISSUE TITLE
CoinCbc.cpp:946:5: error: no matching function for call to 'CbcMain1'

### ISSUE THREAD

**Issue by yurivict** [coin-or/CoinMP#20]
```
CoinCbc.cpp:946:5: error: no matching function for call to 'CbcMain1'
                                CbcMain1(argc, argv, *pCbc->cbc, parameterData);
                                ^~~~~~~~
/usr/local/include/coin/CbcModel.hpp:3258:5: note: candidate function not viable: no known conversion from 'CbcSolverUsefulData' to 'int (*)(CbcModel *, int)' for 4th argument
int CbcMain1(int argc, const char *argv[], CbcModel &babSolver, int(CbcModel *currentSolver, int whereFrom));
    ^
/usr/local/include/coin/CbcModel.hpp:3252:5: note: candidate function not viable: requires 3 arguments, but 4 were provided
int CbcMain1(int argc, const char *argv[], CbcModel &babSolver);
    ^
/usr/local/include/coin/CbcSolver.hpp:306:5: note: candidate function not viable: requires 5 arguments, but 4 were provided
int CbcMain1(int argc, const char *argv[], CbcModel &babSolver, int(CbcModel *currentSolver, int whereFrom), CbcSolverUsefulData &solverData);
    ^
CoinCbc.cpp:953:5: error: no matching function for call to 'CbcMain1'
                                CbcMain1(argc, argv, *pCbc->cbc, parameterData);
                                ^~~~~~~~
/usr/local/include/coin/CbcModel.hpp:3258:5: note: candidate function not viable: no known conversion from 'CbcSolverUsefulData' to 'int (*)(CbcModel *, int)' for 4th argument
int CbcMain1(int argc, const char *argv[], CbcModel &babSolver, int(CbcModel *currentSolver, int whereFrom));
    ^
```

**Comment by yurivict** [comment]
@BjarniMax

Hi,

Do you know why this repository doesn't build? You made several last commits, so maybe you would know?

Thank you,
Yuri

**Comment by tkralphs** [comment]
We are in the middle of the process of fixing up `master` of CoinMP so that it builds with the `master` version of Cbc (which will become stable/3.0). In general, `master` is the development version and isn't guaranteed to work. Right now, it's definitely broken. Sticking with releases is a good idea and as mentioned [here](https://github.com/coin-or/CoinMP/issues/18#issuecomment-669660518), the latest release of CoinMP (1.8.4) builds with the latest release of Cbc (2.10.5).

**Comment by yurivict** [comment]
> Sticking with releases is a good idea and as mentioned here, the latest release of CoinMP (1.8.4) builds with the latest release of Cbc (2.10.5).

The problem I am trying to solve is that 1.8.4 installs its own Cbc and other libraries.

Is there a way to build OpenMP-1.8.4 using only external COIN-OR libraries?

**Comment by tkralphs** [comment]
I'm assuming that happens on FreeBSD because someone packaged Cbc with it on FreeBSD. But if you clone this repo and checkout the tag `releases/1.8.4`, you won't see any Cbc code there. CoinMP *must* link to an external Cbc, there is no other way to build it. If you first build or install Cbc 2.10.5 separately, then put the path to the .pc files into your pkg-config path, and finally build CoinMP 1.8.4, it will link to the separately installed Cbc.

**Comment by yurivict** [comment]
On FreeBSD the port takes this tarball: http://www.coin-or.org/download/source/CoinMP/CoinMP-1.8.4.tgz
It does have Cbc code. And you are right - cloned repo reset to 1.8.4 doesn't have Cbc.

They are somehow different. This causes confusion.

**Comment by yurivict** [comment]
Closing because it was against an unstable master.

**Comment by tkralphs** [comment]
Ah, I see, OK, sorry, yes, it used to say on the Web site that packagers are supposed to get their source from http://www.coin-or.org/download/pkgsource/CoinMP which was set up for that purpose. The other tarball had all the COIN-OR dependencies packaged with it to make it easy for individual users to build from source. Otherwise, it was difficult to figure out what versions of dependencies to get. This was intended to clear up confusion for users, but perhaps created confusion for packagers. Anyway, now you should just get the automatically generated tarball at Github (e.g., https://github.com/coin-or/CoinMP/archive/refs/tags/releases/1.8.4.tar.gz).
